# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.1.0
group=strangequark.variablecopperbulbsignal
java_version=25

# Common
minecraft_version=26.1
mod_name=Variable Copper Bulb Signal
mod_author=Strange Quark
mod_id=variablecopperbulbsignal
license=MIT
credits=
description=This mod changes the comparator output of copper bulb based on its oxidation level. It matches the light level and redstone signal.
minecraft_version_range=[26.1,)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=26.1
parchment_version=2025.10.12

# Fabric
fabric_version=0.144.0+26.1
fabric_loader_version=0.18.4

# Forge
#forge_version=52.1.0
#forge_loader_version_range=[52,)

# NeoForge
neoforge_version=26.1.0.1-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
